import { z } from "zod";

export type DataForSeoListingCandidate = {
  provider: "dataforseo_business_listings"; providerSourceId: string; businessName: string;
  providerCategory: string | null; additionalCategories: string[]; description: string | null;
  fullAddress: string | null; city: string | null; state: string | null; countryCode: string | null;
  latitude: number | null; longitude: number | null; phone: string | null; website: string | null;
  ratingValue: number | null; ratingCount: number | null; claimedIndication: boolean | null;
  operatingStatus: string | null; isInactiveOrClosed: boolean; observedAt: string; mappingIssues: string[];
};
export class DataForSeoProviderError extends Error {
  readonly reference: string; readonly topLevelStatusCode: number | null; readonly taskStatusCode: number | null; readonly taskId: string | null;
  constructor(reference: string, topLevelStatusCode: number | null, taskStatusCode: number | null, taskId: string | null) { super("DataForSEO provider request failed."); this.name="DataForSeoProviderError"; this.reference=reference; this.topLevelStatusCode=topLevelStatusCode; this.taskStatusCode=taskStatusCode; this.taskId=taskId; }
}
const itemSchema=z.object({ type:z.string().optional(), title:z.string().optional(), description:z.string().nullable().optional(), category:z.string().nullable().optional(), additional_categories:z.array(z.string()).nullable().optional(), cid:z.union([z.string(),z.number()]).nullable().optional(), feature_id:z.union([z.string(),z.number()]).nullable().optional(), place_id:z.union([z.string(),z.number()]).nullable().optional(), address:z.string().nullable().optional(), address_info:z.object({city:z.string().nullable().optional(),region:z.string().nullable().optional(),country_code:z.string().nullable().optional()}).passthrough().nullable().optional(), phone:z.string().nullable().optional(), url:z.string().url().nullable().optional(), domain:z.string().nullable().optional(), latitude:z.number().nullable().optional(), longitude:z.number().nullable().optional(), is_claimed:z.boolean().nullable().optional(), rating:z.object({value:z.number().nullable().optional(),votes_count:z.number().int().nullable().optional()}).passthrough().nullable().optional(), work_time:z.object({current_status:z.string().nullable().optional()}).passthrough().nullable().optional() }).passthrough();
const taskSchema=z.object({id:z.string().nullable().optional(),status_code:z.number(),result:z.array(z.object({items:z.array(itemSchema).optional()}).passthrough()).optional(),cost:z.number().nullable().optional()}).passthrough();
const responseSchema=z.object({status_code:z.number(),tasks:z.array(taskSchema)}).passthrough();
const categoriesResponseSchema=z.object({status_code:z.number(),tasks:z.array(z.object({id:z.string().nullable().optional(),status_code:z.number(),result:z.array(z.object({items:z.array(z.object({category:z.string()}).passthrough()).optional()}).passthrough()).optional()}).passthrough())}).passthrough();

export const dataForSeoCategoryMap={Restaurant:"restaurant",Caterer:"caterer",Hotel:"hotel",Supermarket:"supermarket"} as const;
export function mapCampaignCategories(categories:string[]) { const mapped:string[]=[]; const omitted:string[]=[]; for(const category of categories){const value=(dataForSeoCategoryMap as Record<string,string | undefined>)[category]; if(value){if(!mapped.includes(value)) mapped.push(value);} else omitted.push(category);} return {mapped:mapped.slice(0,10),omitted}; }
export function compareConfiguredCategories(supported:Set<string>,categories:string[]){const {mapped,omitted}=mapCampaignCategories(categories); return {confirmedMappings:mapped.filter(value=>supported.has(value)),missingConfiguredMappings:mapped.filter(value=>!supported.has(value)),unmappedCampaignCategories:omitted};}
export function buildDataForSeoRequest(input:{latitude:number;longitude:number;radiusKm:number;categories:string[];limit:number}) { const {latitude,longitude,radiusKm,categories,limit}=input; if(!Number.isFinite(latitude)||latitude < -90||latitude>90) throw new RangeError("latitude must be between -90 and 90"); if(!Number.isFinite(longitude)||longitude < -180||longitude>180) throw new RangeError("longitude must be between -180 and 180"); if(!Number.isInteger(radiusKm)||radiusKm<1||radiusKm>100) throw new RangeError("radius must be between 1 and 100 kilometres"); if(!Number.isInteger(limit)||limit<1||limit>50) throw new RangeError("limit must be between 1 and 50"); const mapping=mapCampaignCategories(categories); if(!mapping.mapped.length||mapping.mapped.length>10) throw new RangeError("between 1 and 10 mapped categories are required"); const fixed=(value:number)=>Number(value.toFixed(7)).toString(); return [{language_code:"en",location_coordinate:`${fixed(latitude)},${fixed(longitude)},${radiusKm}`,categories:mapping.mapped,limit}]; }
function stableId(item:z.infer<typeof itemSchema>){for(const value of [item.place_id,item.feature_id,item.cid]) if(value!==undefined&&value!==null&&String(value).trim()) return String(value); return null;}
export function mapDataForSeoLiveResponse(input:unknown,observedAt=new Date().toISOString()):{candidates:DataForSeoListingCandidate[];issues:string[];taskId:string|null;cost:number;resultCount:number}{const parsed=responseSchema.safeParse(input); if(!parsed.success) throw new DataForSeoProviderError("DATAFORSEO_RESPONSE_INVALID",null,null,null); const task=parsed.data.tasks[0]; if(parsed.data.status_code!==20000||parsed.data.tasks.length!==1||!task||task.status_code!==20000) throw new DataForSeoProviderError("DATAFORSEO_LIVE_STATUS",parsed.data.status_code,task?.status_code??null,task?.id??null); const candidates:DataForSeoListingCandidate[]=[];const issues:string[]=[];let resultCount=0; for(const result of task.result??[]){for(const item of result.items??[]){resultCount++;if(item.type!=="business_listing")continue;const id=stableId(item);if(!id){issues.push("Listing has no stable provider identity.");continue;}const status=item.work_time?.current_status??null;candidates.push({provider:"dataforseo_business_listings",providerSourceId:id,businessName:item.title?.trim()||"",providerCategory:item.category??null,additionalCategories:item.additional_categories??[],description:item.description??null,fullAddress:item.address??null,city:item.address_info?.city??null,state:item.address_info?.region??null,countryCode:item.address_info?.country_code??null,latitude:item.latitude??null,longitude:item.longitude??null,phone:item.phone??null,website:item.url??item.domain??null,ratingValue:item.rating?.value??null,ratingCount:item.rating?.votes_count??null,claimedIndication:item.is_claimed??null,operatingStatus:status,isInactiveOrClosed:status==="temporarily_closed"||status==="closed_forever",observedAt,mappingIssues:[...(item.title?.trim()?[]:["Listing has no business name."]),...(item.address_info?.city?[]:["Listing has no city."]),...(item.category?[]:["Listing has no provider category."]),...(!item.phone?["Listing has no public phone."]:[]),...(!item.url&&!item.domain?["Listing has no public website."]:[])]});}} return {candidates,issues,taskId:task.id??null,cost:task.cost??0,resultCount};}
function requireServerOnly(){ if(typeof window !== "undefined") throw new Error("DataForSEO adapter is server-only."); }
export async function fetchDataForSeoBusinessListings(input:{latitude:number;longitude:number;radiusKm:number;categories:string[];limit:number}) { requireServerOnly(); const body=await request("/v3/business_data/business_listings/search/live",{method:"POST",body:JSON.stringify(buildDataForSeoRequest(input))}); return mapDataForSeoLiveResponse(body); }
async function request(path:string,init:RequestInit){requireServerOnly();const login=process.env.DATAFORSEO_LOGIN,password=process.env.DATAFORSEO_PASSWORD;if(!login||!password) throw new DataForSeoProviderError("DATAFORSEO_NOT_CONFIGURED",null,null,null);const response=await fetch(`https://api.dataforseo.com${path}`,{...init,headers:{Authorization:`Basic ${Buffer.from(`${login}:${password}`).toString("base64")}`,"Content-Type":"application/json",...init.headers},signal:AbortSignal.timeout(20000)});if(!response.ok) throw new DataForSeoProviderError("DATAFORSEO_HTTP_ERROR",null,null,null);return response.json();}
export async function fetchDataForSeoListingCategories(){const body=await request("/v3/business_data/business_listings/categories",{method:"GET"});const parsed=categoriesResponseSchema.safeParse(body);if(!parsed.success) throw new DataForSeoProviderError("DATAFORSEO_CATEGORIES_INVALID",null,null,null);const task=parsed.data.tasks[0];if(parsed.data.status_code!==20000||parsed.data.tasks.length!==1||!task||task.status_code!==20000) throw new DataForSeoProviderError("DATAFORSEO_CATEGORIES_STATUS",parsed.data.status_code,task?.status_code??null,task?.id??null);return new Set((task.result??[]).flatMap(result=>(result.items??[]).map(item=>item.category)));}