import type { DataForSeoListingCandidate } from "./dataforseo-parser.ts";
import type { DiscoveryCandidate, DiscoveryChannel } from "./types.ts";
import { canonicalizeWebsiteHostname, normalizeBusinessName, normalizeLocationComparison, normalizeNigerianPhone } from "../normalization.ts";

export type ProspectIdentity = { id:string; discoverySourceId:string|null; businessName:string; city:string|null };
export type CompletionCandidate = { providerSourceId:string;businessName:string;providerCategory:string|null;mappedCampaignCategory:string|null;providerCategoryIds:string[];additionalCategories:string[];mappingIssues:string[];providerSourceUrl:string|null;description:string|null;fullAddress:string|null;city:string|null;state:string|null;countryCode:string|null;latitude:number|null;longitude:number|null;phone:string|null;website:string|null;ratingValue:number|null;ratingCount:number|null;claimedIndication:boolean|null;operatingStatus:string|null;observedAt:string;normalizedBusinessName:string;normalizedCity:string|null;preparedScore:null;scoreVersion:null;scoreFactors:never[];exactMatchingProspectId:string|null;softMatchWarningCount:number};
export function classifyProviderIdentity(providerId:string,prospects:ProspectIdentity[]){const matches=prospects.filter(x=>x.discoverySourceId===providerId);return{exactId:matches.length===1?matches[0].id:null,multiple:matches.length>1,matchIds:matches.map(x=>x.id)};}
export function conservativeSoftWarningCount(listing:DataForSeoListingCandidate,prospects:ProspectIdentity[],excludedIds:string[]=[]){const name=normalizeBusinessName(listing.businessName);const city=listing.city?normalizeLocationComparison(listing.city):null;if(!city)return 0;return new Set(prospects.filter(x=>!excludedIds.includes(x.id)&&normalizeBusinessName(x.businessName)===name&&normalizeLocationComparison(x.city??"")===city).map(x=>x.id)).size;}
export function toCompletionCandidate(listing:DataForSeoListingCandidate,prospects:ProspectIdentity[]):CompletionCandidate{const exact=classifyProviderIdentity(listing.providerSourceId,prospects);const issues=[...listing.mappingIssues,...(exact.multiple?["Multiple CRM prospects share this provider identity."]:[])];return{providerSourceId:listing.providerSourceId,businessName:listing.businessName,providerCategory:listing.providerCategory,mappedCampaignCategory:listing.mappedCampaignCategory,providerCategoryIds:listing.providerCategoryIds,additionalCategories:listing.additionalCategories,mappingIssues:issues,providerSourceUrl:listing.providerSourceUrl,description:listing.description,fullAddress:listing.fullAddress,city:listing.city,state:listing.state,countryCode:listing.countryCode,latitude:listing.latitude,longitude:listing.longitude,phone:listing.phone,website:listing.website,ratingValue:listing.ratingValue,ratingCount:listing.ratingCount,claimedIndication:listing.claimedIndication,operatingStatus:listing.operatingStatus,observedAt:listing.observedAt,normalizedBusinessName:normalizeBusinessName(listing.businessName),normalizedCity:listing.city?normalizeLocationComparison(listing.city):null,preparedScore:null,scoreVersion:null,scoreFactors:[],exactMatchingProspectId:exact.exactId,softMatchWarningCount:conservativeSoftWarningCount(listing,prospects,exact.matchIds)+(exact.multiple?1:0)};}
export type StagedCaptureInput={status:string;provider:string;providerSourceId:string;providerSourceUrl:string|null;observedAt:string;campaignId:string;campaignCountry:string;businessName:string;mappedCategory:string|null;city:string|null;state:string|null;countryCode:string|null;phone:string|null;website:string|null;operatingStatus:string|null};
export function buildProviderChannels(input:Pick<StagedCaptureInput,"phone"|"website">):DiscoveryChannel[]{const channels:DiscoveryChannel[]=[];if(input.phone&&normalizeNigerianPhone(input.phone))channels.push({platform:"phone",handleOrValue:input.phone,evidence:{provider:"DataForSEO public listing"}});if(input.website&&canonicalizeWebsiteHostname(input.website))channels.push({platform:"website",handleOrValue:input.website,profileUrl:/^https?:\/\//i.test(input.website)?input.website:undefined,evidence:{provider:"DataForSEO public listing"}});return channels;}
export function stagedCaptureReadiness(input:StagedCaptureInput):{candidate:DiscoveryCandidate|null;blockers:string[]}{const blockers:string[]=[];if(!["new","reviewing","duplicate"].includes(input.status))blockers.push("Candidate status cannot be captured.");if(!input.businessName.trim())blockers.push("Business name is missing.");if(!input.mappedCategory)blockers.push("Campaign category is missing.");if(!input.city)blockers.push("Provider city is missing.");if(input.countryCode!=="NG"||normalizeLocationComparison(input.campaignCountry)!=="nigeria")blockers.push("Provider country is unsupported.");if(!input.providerSourceUrl)blockers.push("Provider source URL is missing.");const channels=buildProviderChannels(input);if(!channels.length)blockers.push("No usable public phone or website is available.");if(blockers.length)return{candidate:null,blockers};return{blockers:[],candidate:{provider:input.provider,providerSourceId:input.providerSourceId,sourceUrl:input.providerSourceUrl!,observedAt:input.observedAt,campaignId:input.campaignId,businessName:input.businessName,businessCategory:input.mappedCategory!,city:input.city!,state:input.state??undefined,country:input.campaignCountry,serviceAreaCities:[input.city!],demandBand:"unknown",isInactiveOrClosed:["temporarily_closed","closed_forever"].includes(input.operatingStatus??""),isConsumerOnly:false,channels}};}
export function dismissalTransition(status:string,currentReason:string|null,nextReason:string){const reason=nextReason.trim();if(reason.length<3||reason.length>500)return{allowed:false,idempotent:false,reference:"DISCOVERY_DISMISS_REASON"};if(["new","reviewing","duplicate"].includes(status))return{allowed:true,idempotent:false,reference:null};if(status==="dismissed"&&currentReason?.trim()===reason)return{allowed:true,idempotent:true,reference:null};return{allowed:false,idempotent:false,reference:status==="dismissed"?"DISCOVERY_DISMISS_ALREADY_FINAL":"DISCOVERY_DISMISS_STATE"};}
export function withoutCreateNewForExact<T extends {choice:string}>(choices:T[],hasExact:boolean){return hasExact?choices.filter(x=>x.choice!=="create_new"):choices;}