import "server-only";
import { requireAdmin } from "@/src/lib/admin-auth";
import { createAdminSupabaseClient } from "@/src/lib/supabase/admin";
import { requireSalesScoutDiscoveryEnabled } from "../access";
import { getSalesScoutCampaign, previewSalesScoutCandidate, captureSalesScoutCandidate, type SalesScoutCampaignDto } from "../server";
import { DataForSeoProviderError, fetchDataForSeoBusinessListings, isDataForSeoBusinessListingsConfigured, mapCampaignCategories } from "./dataforseo";
import { dismissalTransition, stagedCaptureReadiness as pureCaptureReadiness, toCompletionCandidate, type ProspectIdentity, type StagedCaptureInput } from "./helpers";

export class SalesScoutDiscoveryError extends Error { constructor(readonly reference:string,message="The discovery operation could not be completed."){super(message);this.name="SalesScoutDiscoveryError";} }
export function hasCompleteDiscoveryConfiguration(c:SalesScoutCampaignDto){return c.discoveryLatitude!=null&&c.discoveryLongitude!=null&&c.discoveryRadiusKm!=null&&c.discoveryDefaultLimit!=null;}
async function auth(){const actor=await requireAdmin();requireSalesScoutDiscoveryEnabled();return actor;}
function dbFail(reference:string,error?:{code?:string}){console.error("Sales Scout discovery database failure",{reference,code:error?.code??null});throw new SalesScoutDiscoveryError(reference);}
export type DiscoveryRunSummary={runId:string;providerTaskId:string;rawResultCount:number;stagedCandidateCount:number;exactDuplicateCount:number;providerCost:number;mappingIssueCount:number};
export type DiscoveryRunRow={id:string;status:string;requested_categories:string[];provider_task_id:string|null;provider_cost_usd:number|null;raw_result_count:number;staged_candidate_count:number;exact_duplicate_count:number;error_reference:string|null;started_at:string;completed_at:string|null};
export type DiscoveryCandidateRow={id:string;scout_campaign_id:string;provider:string;provider_source_id:string;provider_source_url:string|null;business_name:string;provider_category:string|null;mapped_campaign_category:string|null;provider_category_ids:string[];additional_categories:string[];publicDescription:string|null;full_address:string|null;city:string|null;state:string|null;country_code:string|null;latitude:number|null;longitude:number|null;public_phone:string|null;public_website:string|null;rating_value:number|null;rating_count:number|null;claimed_indication:boolean|null;operating_status:string|null;observed_at:string;status:string;exact_matching_prospect_id:string|null;captured_prospect_id:string|null;soft_match_warning_count:number;mapping_issues:string[];dismissal_reason:string|null;first_seen_at:string;last_seen_at:string;seen_count:number};
export type DiscoveryCandidateListRow=Pick<DiscoveryCandidateRow,"id"|"scout_campaign_id"|"provider"|"provider_source_id"|"business_name"|"mapped_campaign_category"|"city"|"state"|"country_code"|"status"|"exact_matching_prospect_id"|"soft_match_warning_count"|"mapping_issues"|"public_phone"|"public_website"|"last_seen_at"|"seen_count">;
export type DiscoveryMembershipRow={discovery_run_id:string;candidate_id:string;is_exact_duplicate:boolean;exact_matching_prospect_id:string|null;soft_match_warning_count:number;created_at:string;marketing_sales_scout_discovery_runs:unknown};
export async function runSalesScoutDiscovery(input:{campaignId:string}):Promise<DiscoveryRunSummary>{const actor=await auth();const campaign=await getSalesScoutCampaign(input.campaignId);if(campaign.status!=="active"||!hasCompleteDiscoveryConfiguration(campaign)||!mapCampaignCategories([...campaign.targetCategories]).mapped.length)throw new SalesScoutDiscoveryError("DISCOVERY_CAMPAIGN_NOT_READY","Campaign discovery configuration is incomplete.");if(!isDataForSeoBusinessListingsConfigured())throw new SalesScoutDiscoveryError("DISCOVERY_PROVIDER_NOT_CONFIGURED");const database=createAdminSupabaseClient();const started=await database.rpc("start_sales_scout_discovery_run",{p_campaign_id:campaign.campaignId,p_categories:[...campaign.targetCategories],p_result_limit:campaign.discoveryDefaultLimit,p_actor_id:actor.id});if(started.error)dbFail("DISCOVERY_START",started.error);const runId=String((started.data as Record<string,unknown>).runId);try{const provider=await fetchDataForSeoBusinessListings({latitude:campaign.discoveryLatitude!,longitude:campaign.discoveryLongitude!,radiusKm:campaign.discoveryRadiusKm!,categories:[...campaign.targetCategories],limit:campaign.discoveryDefaultLimit!},[...campaign.targetCategories]);if(!provider.taskId)throw new SalesScoutDiscoveryError("DISCOVERY_PROVIDER_TASK_MISSING");const ids=provider.candidates.map(x=>x.providerSourceId);const existing=ids.length?await database.from("marketing_prospects").select("id,discovery_source_id,business_name,city").eq("discovery_source","dataforseo_business_listings").in("discovery_source_id",ids).limit(500):{data:[],error:null};if(existing.error)dbFail("DISCOVERY_EXACT_LOOKUP",existing.error);const soft=await database.from("marketing_prospects").select("id,business_name,city,country").eq("country",campaign.country).limit(1000);if(soft.error)dbFail("DISCOVERY_SOFT_LOOKUP",soft.error);let mappingIssueCount=0;
const prospectRows: ProspectIdentity[] = [
  ...(existing.data ?? []).map((row) => ({ id:String(row.id), discoverySourceId:row.discovery_source_id ? String(row.discovery_source_id) : null, businessName:String(row.business_name), city:row.city ? String(row.city) : null })),
  ...(soft.data ?? []).map((row) => ({ id:String(row.id), discoverySourceId:null, businessName:String(row.business_name), city:row.city ? String(row.city) : null })),
];
const candidates=provider.candidates.map((item)=>{const candidate=toCompletionCandidate(item,prospectRows);mappingIssueCount+=candidate.mappingIssues.length;return candidate;});
const completed=await database.rpc("complete_sales_scout_discovery_run",{p_run_id:runId,p_payload:{providerTaskId:provider.taskId,providerCostUsd:provider.cost,rawResultCount:provider.resultCount,candidates},p_actor_id:actor.id});if(completed.error)dbFail("DISCOVERY_COMPLETE",completed.error);const dto=completed.data as Record<string,unknown>;return{runId,providerTaskId:provider.taskId,rawResultCount:provider.resultCount,stagedCandidateCount:Number(dto.stagedCandidateCount),exactDuplicateCount:Number(dto.exactDuplicateCount),providerCost:provider.cost,mappingIssueCount};}catch(error){const reference=error instanceof DataForSeoProviderError?error.reference:error instanceof SalesScoutDiscoveryError?error.reference:"DISCOVERY_RUN_FAILED";const failed=await database.rpc("fail_sales_scout_discovery_run",{p_run_id:runId,p_error_reference:reference,p_error_safe_message:"Discovery could not be completed.",p_actor_id:actor.id});if(failed.error)console.error("Discovery failure marking failed",{reference,code:failed.error.code});throw new SalesScoutDiscoveryError(reference);}}
export async function listSalesScoutDiscoveryRuns({campaignId,page=1,pageSize=20}:{campaignId:string;page?:number;pageSize?:number}){await auth();pageSize=Math.min(50,Math.max(1,pageSize));const from=(Math.max(1,page)-1)*pageSize;const q=await createAdminSupabaseClient().from("marketing_sales_scout_discovery_runs").select("id,status,requested_categories,provider_task_id,provider_cost_usd,raw_result_count,staged_candidate_count,exact_duplicate_count,error_reference,started_at,completed_at",{count:"exact"}).eq("scout_campaign_id",campaignId).order("started_at",{ascending:false}).range(from,from+pageSize-1);if(q.error)dbFail("DISCOVERY_RUN_LIST",q.error);return{rows:(q.data??[]) as DiscoveryRunRow[],count:q.count??0};}
export async function listSalesScoutDiscoveryCandidates({campaignId,status,search,mappingIssueOnly,page=1,pageSize=25}:{campaignId:string;status?:string;search?:string;mappingIssueOnly?:boolean;page?:number;pageSize?:number}){await auth();pageSize=Math.min(50,Math.max(1,pageSize));const from=(Math.max(1,page)-1)*pageSize;let q=createAdminSupabaseClient().from("marketing_sales_scout_discovery_candidates").select("id,scout_campaign_id,provider,provider_source_id,business_name,mapped_campaign_category,city,state,country_code,status,exact_matching_prospect_id,soft_match_warning_count,mapping_issues,public_phone,public_website,last_seen_at,seen_count",{count:"exact"}).eq("scout_campaign_id",campaignId).order("last_seen_at",{ascending:false});if(status)q=q.eq("status",status);if(search)q=q.ilike("business_name",`%${search.replaceAll("%","")}%`);if(mappingIssueOnly)q=q.neq("mapping_issues","[]");const out=await q.range(from,from+pageSize-1);if(out.error)dbFail("DISCOVERY_CANDIDATE_LIST",out.error);return{rows:(out.data??[]) as DiscoveryCandidateListRow[],count:out.count??0};}
export async function getSalesScoutDiscoveryCandidate(id:string){await auth();const db=createAdminSupabaseClient();const row=await db.from("marketing_sales_scout_discovery_candidates").select("id,scout_campaign_id,provider,provider_source_id,provider_source_url,business_name,provider_category,mapped_campaign_category,provider_category_ids,additional_categories,publicDescription:public_description,full_address,city,state,country_code,latitude,longitude,public_phone,public_website,rating_value,rating_count,claimed_indication,operating_status,observed_at,status,exact_matching_prospect_id,captured_prospect_id,soft_match_warning_count,mapping_issues,dismissal_reason,first_seen_at,last_seen_at,seen_count").eq("id",id).maybeSingle();if(row.error)dbFail("DISCOVERY_CANDIDATE_DETAIL",row.error);if(!row.data)throw new SalesScoutDiscoveryError("DISCOVERY_CANDIDATE_NOT_FOUND");const candidate=row.data;const history=await db.from("marketing_sales_scout_discovery_run_candidates").select("discovery_run_id,candidate_id,is_exact_duplicate,exact_matching_prospect_id,soft_match_warning_count,created_at,marketing_sales_scout_discovery_runs(status,started_at,completed_at,provider_task_id)").eq("candidate_id",id).order("created_at",{ascending:false}).limit(100);if(history.error)dbFail("DISCOVERY_HISTORY",history.error);const prospectIds=[candidate.exact_matching_prospect_id,candidate.captured_prospect_id].filter((value):value is string=>Boolean(value));const prospects=prospectIds.length?await db.from("marketing_prospects").select("id,business_name,city").in("id",prospectIds).limit(2):{data:[],error:null};if(prospects.error)dbFail("DISCOVERY_LINKED_PROSPECTS",prospects.error);const summaries=(prospects.data??[]).map((prospect)=>({id:String(prospect.id),businessName:String(prospect.business_name),city:prospect.city?String(prospect.city):null}));return{candidate:candidate as DiscoveryCandidateRow,history:(history.data??[]) as DiscoveryMembershipRow[],exactProspect:summaries.find((prospect)=>prospect.id===candidate.exact_matching_prospect_id)??null,capturedProspect:summaries.find((prospect)=>prospect.id===candidate.captured_prospect_id)??null,readiness:await stagedCaptureReadiness(candidate as Record<string,unknown>)};}
export async function stagedCaptureReadiness(row: Record<string, unknown>) {
  const campaign = await getSalesScoutCampaign(String(row.scout_campaign_id));
  const input: StagedCaptureInput = {
    status:String(row.status), provider:String(row.provider), providerSourceId:String(row.provider_source_id),
    providerSourceUrl:row.provider_source_url ? String(row.provider_source_url) : null,
    observedAt:String(row.observed_at), campaignId:String(row.scout_campaign_id), campaignCountry:campaign.country,
    businessName:String(row.business_name), mappedCategory:row.mapped_campaign_category ? String(row.mapped_campaign_category) : null,
    city:row.city ? String(row.city) : null, state:row.state ? String(row.state) : null,
    countryCode:row.country_code ? String(row.country_code) : null, phone:row.public_phone ? String(row.public_phone) : null,
    website:row.public_website ? String(row.public_website) : null, operatingStatus:row.operating_status ? String(row.operating_status) : null,
  };
  return pureCaptureReadiness(input);
}
export async function previewStagedSalesScoutCandidate(id:string){const detail=await getSalesScoutDiscoveryCandidate(id);if(!detail.readiness.candidate)throw new SalesScoutDiscoveryError("DISCOVERY_CAPTURE_BLOCKED");return previewSalesScoutCandidate(detail.readiness.candidate);}
export async function captureStagedSalesScoutCandidate({candidateId,resolution}:{candidateId:string;resolution:unknown}){const actor=await auth();const detail=await getSalesScoutDiscoveryCandidate(candidateId);if(!detail.readiness.candidate)throw new SalesScoutDiscoveryError("DISCOVERY_CAPTURE_BLOCKED");const result=await captureSalesScoutCandidate({candidate:detail.readiness.candidate,resolution});const update=await createAdminSupabaseClient().from("marketing_sales_scout_discovery_candidates").update({status:"captured",captured_prospect_id:result.prospectId,reviewed_by:actor.id,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",candidateId).in("status",["new","reviewing","duplicate"]).select("id,status,captured_prospect_id").maybeSingle();if(update.error)dbFail("DISCOVERY_CAPTURE_MARK",update.error);if(!update.data)throw new SalesScoutDiscoveryError("DISCOVERY_CAPTURE_STATE_CHANGED");return result;}
export async function dismissSalesScoutDiscoveryCandidate({candidateId,reason}:{candidateId:string;reason:string}){const actor=await auth();reason=reason.trim();const db=createAdminSupabaseClient();const current=await db.from("marketing_sales_scout_discovery_candidates").select("status,dismissal_reason").eq("id",candidateId).single();if(current.error)dbFail("DISCOVERY_DISMISS_LOAD",current.error);if(!current.data)throw new SalesScoutDiscoveryError("DISCOVERY_CANDIDATE_NOT_FOUND");const transition=dismissalTransition(current.data.status,current.data.dismissal_reason,reason);if(!transition.allowed)throw new SalesScoutDiscoveryError(transition.reference??"DISCOVERY_DISMISS_STATE");if(transition.idempotent)return{idempotent:true};const out=await db.from("marketing_sales_scout_discovery_candidates").update({status:"dismissed",dismissal_reason:reason,reviewed_by:actor.id,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",candidateId).in("status",["new","reviewing","duplicate"]).select("id,status").maybeSingle();if(out.error)dbFail("DISCOVERY_DISMISS",out.error);if(!out.data)throw new SalesScoutDiscoveryError("DISCOVERY_DISMISS_STATE_CHANGED");return{idempotent:false};}