import Link from "next/link";
import { notFound } from "next/navigation";
import { DiscoveryRunForm } from "@/src/components/sales-scout/discovery-run-form";
import { requireAdmin } from "@/src/lib/admin-auth";
import { isSalesScoutDiscoveryEnabled,isSalesScoutEnabled } from "@/src/lib/sales-scout/access";
import { hasCompleteDiscoveryConfiguration,listSalesScoutDiscoveryCandidates,listSalesScoutDiscoveryRuns,productionResearchCostCeiling,providerConfigurationStatus } from "@/src/lib/sales-scout/discovery/server";
import { listAllSalesScoutCampaigns } from "@/src/lib/sales-scout/server";
import { unsupportedStructuredCategories } from "@/src/lib/sales-scout/territory";

export const dynamic="force-dynamic";const PAGE=25;
function positive(value?:string){const number=Number.parseInt(value??"1",10);return Number.isFinite(number)&&number>0?number:1;}
function href(query:Record<string,string|undefined>,key:string,value:number){const params=new URLSearchParams();for(const[name,item]of Object.entries(query))if(item)params.set(name,item);params.set(key,String(value));return`?${params}`;}
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){await requireAdmin();if(!isSalesScoutEnabled()||!isSalesScoutDiscoveryEnabled())notFound();const query=await searchParams;const campaigns=await listAllSalesScoutCampaigns();const campaign=campaigns.find(item=>item.campaignId===query.campaignId)??campaigns.find(item=>item.status==="active")??campaigns[0];if(!campaign)return <main className="p-6">Create a Sales Scout campaign first.</main>;const status=providerConfigurationStatus();const unsupported=unsupportedStructuredCategories(campaign.targetCategories);const costs=productionResearchCostCeiling({categories:campaign.targetCategories.length,coordinatesConfigured:campaign.discoveryLatitude!=null&&campaign.discoveryLongitude!=null,resultLimit:campaign.discoveryDefaultLimit??20,maxEnrichmentCandidates:campaign.maxEnrichmentCandidates??6});const runPage=positive(query.runPage),candidatePage=positive(query.candidatePage);const[runs,candidates]=await Promise.all([listSalesScoutDiscoveryRuns({campaignId:campaign.campaignId,page:runPage,pageSize:20}),listSalesScoutDiscoveryCandidates({campaignId:campaign.campaignId,status:query.status,search:query.search,filter:query.filter,page:candidatePage,pageSize:PAGE})]);return <main className="space-y-6 p-6"><header><Link href="/admin/marketing/sales-scout" className="font-bold text-green-800">Back to Sales Scout</Link><h1 className="text-3xl font-bold">Nigeria Revenue Mode</h1><p>Structured Geoapify discovery, bounded contact research, entity matching, and owner-controlled outreach readiness. No outreach is sent.</p></header>
<form method="get" className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label><b className="block">Campaign</b><select name="campaignId" defaultValue={campaign.campaignId} className="rounded border p-2">{campaigns.map(item=><option key={item.campaignId} value={item.campaignId}>{item.name}</option>)}</select></label><label><b className="block">Candidate status</b><select name="status" defaultValue={query.status??""} className="rounded border p-2"><option value="">All</option>{["new","reviewing","duplicate","captured","dismissed"].map(value=><option key={value}>{value}</option>)}</select></label><label><b className="block">Priority/readiness/contact</b><select name="filter" defaultValue={query.filter??""} className="rounded border p-2"><option value="">All</option>{["highest_opportunity","manual_review_ready","outreach_ready","has_phone","has_whatsapp","has_instagram","has_facebook","has_email","needs_research","captured","dismissed"].map(value=><option key={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label><b className="block">Search</b><input name="search" defaultValue={query.search} maxLength={100} className="rounded border p-2"/></label><button className="rounded-full bg-green-800 px-4 py-2 text-white">Apply</button></form>
<section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">{campaign.name}</h2><p>{campaign.city}, {campaign.state}, Nigeria · {campaign.discoveryRadiusKm} km · {campaign.discoveryDefaultLimit} results/category · {campaign.maxEnrichmentCandidates} researched</p><p>{campaign.targetCategories.join(", ")}</p><div className="mt-3 grid gap-2 sm:grid-cols-4"><p className={status.geoapify?"text-green-800":"text-red-800"}>Geoapify: {status.geoapify?"configured":"not configured"}</p><p className={status.serpapi?"text-green-800":"text-amber-800"}>Public web / SerpApi: {status.serpapi?"enabled":"disabled or not configured"}</p><p>Tavily: production-disabled</p><p>DataForSEO: disabled legacy adapter</p></div>{unsupported.length?<p className="mt-3 rounded border border-amber-300 bg-amber-50 p-3">Structured discovery is not yet supported for: {unsupported.join(", ")}. No broad fallback will run.</p>:null}<dl className="mt-3 grid gap-2 sm:grid-cols-5"><div><dt className="font-bold">Max Geoapify seed calls</dt><dd>{costs.maximumGeoapifyCalls}</dd></div><div><dt className="font-bold">Max Place Details calls</dt><dd>{costs.maximumGeoapifyPlaceDetailsCalls}</dd></div><div><dt className="font-bold">Max public-web searches</dt><dd>{status.serpapi?costs.maximumPublicWebSearchCalls:0}</dd></div><div><dt className="font-bold">Per candidate</dt><dd>4 web searches</dd></div><div><dt className="font-bold">Max website pages</dt><dd>{costs.maximumOfficialWebsitePages}</dd></div></dl><DiscoveryRunForm campaignId={campaign.campaignId} disabled={campaign.status!=="active"||!hasCompleteDiscoveryConfiguration(campaign)||unsupported.length>0||!status.geoapify}/></section>
<section><h2 className="text-xl font-bold">Recent runs</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Started</th><th>Method/status</th><th>Raw/seeds/staged</th><th>Enrichment and calls</th><th>Readiness</th><th>Warnings</th></tr></thead><tbody>{runs.rows.map(run=><tr key={run.id} className="border-b"><td className="p-2">{new Date(run.started_at).toLocaleString("en-NG")}</td><td>{run.research_method??run.provider}<br/>{run.status}</td><td>{run.raw_result_count} / {run.structured_seed_count} / {run.staged_candidate_count}</td><td>{run.enrichment_completed_count}/{run.enrichment_attempted_count} · Geoapify {run.provider_credits.geoapify??0} · public web {run.provider_credits.serpapi??0}</td><td>{run.manual_review_ready_count} manual / {run.outreach_ready_count} verified</td><td>{run.warning_references.join(", ")||run.error_reference||"None"}</td></tr>)}</tbody></table></div><nav className="mt-3 flex gap-4">{runPage>1?<Link href={href(query,"runPage",runPage-1)}>Previous runs</Link>:null}{runPage*20<runs.count?<Link href={href(query,"runPage",runPage+1)}>Next runs</Link>:null}</nav></section>
<section><h2 className="text-xl font-bold">Staged candidates ({candidates.count})</h2><div className="grid gap-3">{candidates.rows.map(candidate=>{const contacts=candidate.contact_evidence??[];const highest=contacts.some(contact=>contact.confidence==="verified")?"verified":contacts.length?"plausible":"needs research";const opportunity=candidate.confidence_summary?.opportunity;return <Link key={candidate.id} href={`/admin/marketing/sales-scout/discover/${candidate.id}`} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-2"><b>{candidate.business_name}</b><span className="rounded-full bg-green-900 px-3 py-1 font-bold text-white">Opportunity {opportunity?.score??"—"}/100</span></div><p>{candidate.mapped_campaign_category??"Needs category review"} · {[candidate.city??campaign.city,candidate.state].filter(Boolean).join(", ")}</p><div className="mt-2 flex flex-wrap gap-2">{[...new Set(contacts.map(contact=>contact.route))].map(route=><span key={route} className="rounded-full bg-stone-100 px-2 py-1 text-xs">{route}</span>)}<span className="rounded-full bg-amber-50 px-2 py-1 text-xs">highest: {highest}</span>{candidate.manual_review_ready?<span className="rounded-full bg-blue-50 px-2 py-1 text-xs">manual review ready</span>:<span className="rounded-full bg-amber-50 px-2 py-1 text-xs">needs research</span>}{candidate.outreach_ready?<span className="rounded-full bg-green-50 px-2 py-1 text-xs">owner-contact ready</span>:null}</div><p className="mt-2 text-sm">{opportunity?.whyPursue??(contacts.length?"Review the available public contact evidence.":"Research a credible public contact route.")}</p><p className="mt-1 text-sm font-medium">Next: {opportunity?.recommendedNextAction??"Open candidate evidence."}</p></Link>;})}</div><nav className="mt-3 flex gap-4">{candidatePage>1?<Link href={href(query,"candidatePage",candidatePage-1)}>Previous candidates</Link>:null}{candidatePage*PAGE<candidates.count?<Link href={href(query,"candidatePage",candidatePage+1)}>Next candidates</Link>:null}</nav></section></main>;}
