import {expect,test} from "@playwright/test";
const widths=[320,360,390,412];
for(const width of widths)test(`public drawer renders above the page at ${width}px`,async({page})=>{await page.setViewportSize({width,height:800});await page.goto("/about");await page.getByRole("button",{name:"Open menu"}).click();const drawer=page.getByRole("dialog",{name:"Menu"});await expect(drawer).toBeVisible();const box=await drawer.boundingBox();expect(box?.width).toBeGreaterThan(Math.min(width*.75,300));await expect(drawer.getByRole("link",{name:"Shop",exact:true})).toBeVisible();await expect(drawer.getByRole("link",{name:"Contact",exact:true})).toBeVisible();await expect(drawer.getByText("Admin",{exact:false})).toHaveCount(0);expect(await page.locator("body").evaluate((body)=>getComputedStyle(body).overflow)).toBe("hidden");await page.keyboard.press("Escape");await expect(drawer).toBeHidden();expect(await page.locator("body").evaluate((body)=>getComputedStyle(body).overflow)).not.toBe("hidden")});
test("navigation and history do not retain the drawer",async({page})=>{await page.setViewportSize({width:390,height:800});await page.goto("/about");await page.getByRole("button",{name:"Open menu"}).click();await page.getByRole("dialog",{name:"Menu"}).getByRole("link",{name:"Shop",exact:true}).click();await expect(page).toHaveURL(/\/shop/);await expect(page.getByRole("dialog",{name:"Menu"})).toHaveCount(0);await page.goBack();await expect(page.getByRole("dialog",{name:"Menu"})).toHaveCount(0)});
test("install remains discoverable and opens fallback help",async({page})=>{await page.setViewportSize({width:390,height:800});await page.goto("/about");await page.getByRole("button",{name:"Open menu"}).click();await page.getByRole("dialog",{name:"Menu"}).getByRole("button",{name:"Install Shields Farms"}).click();await expect(page.getByRole("dialog",{name:/Install Shields Farms/})).toBeVisible();await expect(page.getByText(/Install app|Add to Home Screen/).first()).toBeVisible();await expect(page.getByRole("dialog",{name:"Menu"})).toHaveCount(0);await page.getByRole("button",{name:"Close",exact:true}).click();await expect(page.getByRole("contentinfo").getByRole("button",{name:"Install Shields Farms"})).toBeVisible()});
test("iOS receives Home Screen instructions",async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},userAgent:"Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1"});const page=await context.newPage();await page.goto("/about");await page.getByRole("button",{name:"Open menu"}).click();await page.getByRole("dialog",{name:"Menu"}).getByRole("button",{name:"Install Shields Farms"}).click();await expect(page.getByText("Select Add to Home Screen.")).toBeVisible();await expect(page.getByText("Launch Shields Farms from the Home Screen.")).toBeVisible();await context.close()});
test("official Google tag is consent gated and excluded from Admin",async({page})=>{await page.goto("/about");await expect(page.locator('script[src*="googletagmanager.com/gtag/js"]')).toHaveCount(0);await page.getByRole("button",{name:"Accept All"}).click();await expect(page.locator('script[src*="googletagmanager.com/gtag/js?id=G-LKED7BF5S6"]')).toHaveCount(1);await expect.poll(()=>page.evaluate(()=>Array.isArray(window.dataLayer))).toBe(true);await page.goto("/admin/login");await expect(page.locator('script[src*="googletagmanager.com/gtag/js"]')).toHaveCount(0)});
for(const width of [768,1024,1440])test(`${width}px desktop header has no horizontal overflow`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto("/about");await expect(page.getByRole("button",{name:"Open menu"})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)});
test("public manifest and service worker responses are production-safe",async({request})=>{const manifest=await request.get("/manifest.webmanifest");expect(manifest.ok()).toBe(true);expect(manifest.headers()["content-type"]).toContain("application/manifest+json");const data=await manifest.json();expect(data.start_url).toBe("/");expect(data.scope).toBe("/");expect(data.display).toBe("standalone");expect(data.shortcuts.map((item:{url:string})=>item.url)).toEqual(["/shop","/track-order"]);expect(JSON.stringify(data)).not.toContain("/admin");const worker=await request.get("/sw.js");expect(worker.ok()).toBe(true);expect(worker.headers()["content-type"]).toContain("application/javascript");expect(worker.headers()["cache-control"]).toContain("no-store");expect(worker.headers()["service-worker-allowed"]).toBe("/")});
