"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {requireAdmin} from "@/src/lib/admin-auth";
import {prospectStages} from "@/src/lib/marketing-prospects";
import {createAdminSupabaseClient} from "@/src/lib/supabase/admin";
export type ProspectActionState={ok:boolean;message:string};
const uuid=z.string().uuid();const optional=(max:number)=>z.string().trim().max(max).transform((value)=>value||null);const stage=z.enum(prospectStages);const activity=z.enum(["note","phone_call","whatsapp","email","meeting","proposal_sent","quotation_sent","follow_up","stage_change","trial_order","won","lost"]);
const refresh=(id:string)=>{revalidatePath("/admin/marketing/prospects");revalidatePath(`/admin/marketing/prospects/${id}`);revalidatePath("/admin/marketing/overview");};
type DbError={code?:string;message?:string;details?:string;hint?:string};
function safeDbField(value:unknown){if(typeof value!=="string")return null;if(/failing row|contains \(/i.test(value))return"[redacted row detail]";return value.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,"[redacted email]").replace(/\+?\d[\d\s()-]{7,}\d/g,"[redacted phone]").slice(0,300);}
function logDb(code:string,error:unknown){const db=error as DbError;console.error("Prospect workflow database error",{internalCode:code,code:db?.code??null,message:safeDbField(db?.message),details:safeDbField(db?.details),hint:safeDbField(db?.hint)});}
function stageFailure(error:unknown):ProspectActionState{const db=error as DbError;if(db?.code==="P0002")return{ok:false,message:"The prospect no longer exists."};if(db?.code==="22023")return{ok:false,message:"That pipeline stage is invalid."};if(["PGRST202","PGRST204","42P01","42703"].includes(db?.code??""))return{ok:false,message:"Prospect history is unavailable because the database schema is incomplete."};return{ok:false,message:"The pipeline could not be updated. Reference: PROSPECT_STAGE_DB_ERROR."};}
export async function updateProspectAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{await requireAdmin();const value=z.object({id:uuid,business_name:z.string().trim().min(1).max(200),business_category:optional(120),contact_person:optional(200),contact_email:z.string().trim().email().or(z.literal("")).transform((v)=>v||null),contact_phone:optional(80),requirements:optional(2000),estimated_value:z.coerce.number().min(0),expected_frequency:optional(120),source:optional(120),assigned_follow_up_at:optional(80),notes:optional(3000),inquiry_id:z.string().uuid().or(z.literal("")).transform((v)=>v||null),order_id:z.string().uuid().or(z.literal("")).transform((v)=>v||null)}).parse(Object.fromEntries(formData));const {id,...updates}=value;const {error}=await createAdminSupabaseClient().from("marketing_prospects").update({...updates,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;refresh(id);return{ok:true,message:"Prospect details saved."};}catch(error){console.error("Prospect update failed",{code:"PROSPECT_UPDATE_FAILED",error:error instanceof Error?error.name:"UnknownError"});return{ok:false,message:"The prospect could not be updated."};}}
export async function changeProspectStageAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{const user=await requireAdmin();const value=z.object({id:uuid,stage,summary:optional(500)}).parse(Object.fromEntries(formData));const {data,error}=await createAdminSupabaseClient().rpc("change_marketing_prospect_stage",{p_prospect_id:value.id,p_stage:value.stage,p_summary:value.summary,p_created_by:user.id});if(error)throw error;refresh(value.id);const changed=Array.isArray(data)?data[0]?.changed:true;return{ok:true,message:changed?`Prospect moved to ${value.stage.replaceAll("_"," ")}.`:"Prospect is already at that stage."};}catch(error){logDb("PROSPECT_STAGE_DB_ERROR",error);return stageFailure(error);}}
export async function addProspectActivityAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{const user=await requireAdmin();const value=z.object({prospect_id:uuid,activity_type:activity,summary:z.string().trim().min(1).max(2000),occurred_at:optional(80),next_follow_up_at:optional(80)}).parse(Object.fromEntries(formData));const {error}=await createAdminSupabaseClient().rpc("record_marketing_prospect_activity",{p_prospect_id:value.prospect_id,p_activity_type:value.activity_type,p_summary:value.summary,p_occurred_at:value.occurred_at,p_next_follow_up_at:value.next_follow_up_at,p_created_by:user.id});if(error)throw error;refresh(value.prospect_id);return{ok:true,message:"Activity recorded."};}catch(error){logDb("PROSPECT_ACTIVITY_DB_ERROR",error);const state=stageFailure(error);return state.message.includes("pipeline stage")?{ok:false,message:"That activity type is invalid."}:state.message.includes("pipeline could")?{ok:false,message:"The activity could not be recorded. Reference: PROSPECT_ACTIVITY_DB_ERROR."}:state;}}
export async function completeProspectFollowUpAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{const user=await requireAdmin();const id=uuid.parse(formData.get("id"));const summary=z.string().trim().max(500).parse(formData.get("summary")||"Follow-up completed.");const {error}=await createAdminSupabaseClient().rpc("complete_marketing_prospect_follow_up",{p_prospect_id:id,p_summary:summary,p_created_by:user.id});if(error)throw error;refresh(id);return{ok:true,message:"Follow-up completed."};}catch(error){logDb("PROSPECT_FOLLOW_UP_DB_ERROR",error);const state=stageFailure(error);return state.message.includes("pipeline could")?{ok:false,message:"The follow-up could not be completed. Reference: PROSPECT_FOLLOW_UP_DB_ERROR."}:state;}}
