"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {requireAdmin} from "@/src/lib/admin-auth";
import {prospectStages} from "@/src/lib/marketing-prospects";
import {createAdminSupabaseClient} from "@/src/lib/supabase/admin";
export type ProspectActionState={ok:boolean;message:string};
const uuid=z.string().uuid();const optional=(max:number)=>z.string().trim().max(max).transform((value)=>value||null);const stage=z.enum(prospectStages);const activity=z.enum(["note","phone_call","whatsapp","email","meeting","proposal_sent","quotation_sent","follow_up","stage_change","trial_order","won","lost"]);
const refresh=(id:string)=>{revalidatePath("/admin/marketing/prospects");revalidatePath(`/admin/marketing/prospects/${id}`);revalidatePath("/admin/marketing/overview");};
export async function updateProspectAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{await requireAdmin();const value=z.object({id:uuid,business_name:z.string().trim().min(1).max(200),business_category:optional(120),contact_person:optional(200),contact_email:z.string().trim().email().or(z.literal("")).transform((v)=>v||null),contact_phone:optional(80),requirements:optional(2000),estimated_value:z.coerce.number().min(0),expected_frequency:optional(120),source:optional(120),assigned_follow_up_at:optional(80),notes:optional(3000),inquiry_id:z.string().uuid().or(z.literal("")).transform((v)=>v||null),order_id:z.string().uuid().or(z.literal("")).transform((v)=>v||null)}).parse(Object.fromEntries(formData));const {id,...updates}=value;const {error}=await createAdminSupabaseClient().from("marketing_prospects").update({...updates,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;refresh(id);return{ok:true,message:"Prospect details saved."};}catch(error){console.error("Prospect update failed",{code:"PROSPECT_UPDATE_FAILED",error:error instanceof Error?error.name:"UnknownError"});return{ok:false,message:"The prospect could not be updated."};}}
export async function changeProspectStageAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{const user=await requireAdmin();const value=z.object({id:uuid,stage,summary:optional(500)}).parse(Object.fromEntries(formData));const db=createAdminSupabaseClient();const current=await db.from("marketing_prospects").select("stage").eq("id",value.id).single();if(current.error)throw current.error;const from=stage.parse(current.data.stage);if(from===value.stage)return{ok:true,message:"Prospect is already at that stage."};const now=new Date().toISOString();const updated=await db.from("marketing_prospects").update({stage:value.stage,updated_at:now}).eq("id",value.id);if(updated.error)throw updated.error;const history=await db.from("marketing_prospect_activities").insert({prospect_id:value.id,activity_type:value.stage==="won"?"won":value.stage==="lost"?"lost":"stage_change",stage_from:from,stage_to:value.stage,summary:value.summary||`Stage changed from ${from} to ${value.stage}.`,occurred_at:now,created_by:user.id});if(history.error)throw history.error;refresh(value.id);return{ok:true,message:`Stage updated to ${value.stage.replaceAll("_"," ")}.`};}catch(error){console.error("Prospect stage update failed",{code:"PROSPECT_STAGE_FAILED",error:error instanceof Error?error.name:"UnknownError"});return{ok:false,message:"The stage could not be updated. Check that the activity migration is applied."};}}
export async function addProspectActivityAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{const user=await requireAdmin();const value=z.object({prospect_id:uuid,activity_type:activity,summary:z.string().trim().min(1).max(2000),occurred_at:optional(80),next_follow_up_at:optional(80)}).parse(Object.fromEntries(formData));const db=createAdminSupabaseClient();const occurred=value.occurred_at||new Date().toISOString();const inserted=await db.from("marketing_prospect_activities").insert({...value,occurred_at:occurred,created_by:user.id});if(inserted.error)throw inserted.error;const updates:Record<string,unknown>={updated_at:new Date().toISOString()};if(["phone_call","whatsapp","email","meeting","follow_up"].includes(value.activity_type))updates.last_contact_at=occurred;if(value.next_follow_up_at)updates.assigned_follow_up_at=value.next_follow_up_at;const updated=await db.from("marketing_prospects").update(updates).eq("id",value.prospect_id);if(updated.error)throw updated.error;refresh(value.prospect_id);return{ok:true,message:"Activity recorded."};}catch(error){console.error("Prospect activity failed",{code:"PROSPECT_ACTIVITY_FAILED",error:error instanceof Error?error.name:"UnknownError"});return{ok:false,message:"The activity could not be recorded."};}}
export async function completeProspectFollowUpAction(_:ProspectActionState,formData:FormData):Promise<ProspectActionState>{try{const user=await requireAdmin();const id=uuid.parse(formData.get("id"));const summary=z.string().trim().max(500).parse(formData.get("summary")||"Follow-up completed.");const now=new Date().toISOString();const db=createAdminSupabaseClient();const update=await db.from("marketing_prospects").update({assigned_follow_up_at:null,last_contact_at:now,updated_at:now}).eq("id",id);if(update.error)throw update.error;const history=await db.from("marketing_prospect_activities").insert({prospect_id:id,activity_type:"follow_up",summary,occurred_at:now,created_by:user.id});if(history.error)throw history.error;refresh(id);return{ok:true,message:"Follow-up completed."};}catch(error){console.error("Follow-up completion failed",{code:"PROSPECT_FOLLOW_UP_FAILED",error:error instanceof Error?error.name:"UnknownError"});return{ok:false,message:"The follow-up could not be completed."};}}
