"use client";
import { useActionState } from "react";
import { submitContactInquiry, type ContactState } from "./actions";

const types = [["product_availability","Product availability"],["order_support","Order support"],["bulk_business_supply","Bulk/business supply"],["delivery_question","Delivery question"],["partnership","Partnership"],["other","Other"]] as const;
const initialContactState: ContactState = { ok: false, delivered: false, message: "", fieldErrors: {}, values: {} };
export function ContactForm() {
  const [state, action, pending] = useActionState(submitContactInquiry, initialContactState);
  const field = (name: string) => state.fieldErrors[name]?.[0];
  return <form action={action} className="grid gap-5 rounded-lg bg-white p-6 shadow-sm" noValidate><div className="absolute -left-[9999px]" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off" /></label></div><p className="rounded-lg bg-amber-50 p-3 text-sm font-semibold leading-6 text-amber-900">For urgent orders, call or WhatsApp Shields Farms directly.</p>{state.message ? <p role="status" className={`rounded-lg p-3 text-sm font-bold ${state.ok ? "bg-green-50 text-green-900" : "bg-red-50 text-red-800"}`}>{state.message}</p> : null}<div className="grid gap-5 md:grid-cols-2"><Field name="full_name" label="Full name *" value={state.values.full_name} error={field("full_name")} /><Field name="phone" label="Phone number" value={state.values.phone} error={field("phone")} /></div><Field name="email" label="Email *" type="email" value={state.values.email} error={field("email")} /><label className="grid gap-2 text-sm font-semibold text-stone-800">Inquiry type *<select name="inquiry_type" defaultValue={state.values.inquiry_type ?? ""} aria-invalid={field("inquiry_type") ? true : undefined} className="h-12 rounded-lg border border-stone-200 px-4"><option value="">Choose one</option>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{field("inquiry_type") ? <span className="text-xs font-bold text-red-700">{field("inquiry_type")}</span> : null}</label><label className="grid gap-2 text-sm font-semibold text-stone-800">Message *<textarea name="message" defaultValue={state.values.message} rows={6} aria-invalid={field("message") ? true : undefined} className="rounded-lg border border-stone-200 px-4 py-3" />{field("message") ? <span className="text-xs font-bold text-red-700">{field("message")}</span> : null}</label><button disabled={pending} className="h-12 rounded-full bg-green-800 px-6 text-sm font-bold text-white disabled:opacity-60">{pending ? "Sending..." : "Send message"}</button></form>;
}
function Field({ name, label, type="text", value, error }: { name: string; label: string; type?: string; value?: string; error?: string }) { return <label className="grid gap-2 text-sm font-semibold text-stone-800">{label}<input name={name} type={type} defaultValue={value} aria-invalid={error ? true : undefined} className="h-12 rounded-lg border border-stone-200 px-4" />{error ? <span className="text-xs font-bold text-red-700">{error}</span> : null}</label>; }
