import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(new URL("../" + path, import.meta.url), "utf8");
const page = read("app/business-supply/page.tsx");
const form = read("app/business-supply/business-supply-form.tsx");
const route = read("app/api/business-supply/inquiries/route.ts");
const schema = read("src/lib/business-supply-inquiry.ts");
const admin = read("app/admin/(protected)/inquiries/page.tsx");
const migration = read("database/20260728_business_export_inquiries.sql");
const redirect = read("app/go/[slug]/route.ts");

assert.match(page, /A practical supply partner for food businesses/);
assert.match(page, /Export enquiries for selected Nigerian agricultural produce/);
assert.match(form, /bulk_business_supply/);
assert.match(form, /export_supply/);
assert.match(schema, /acknowledgement: z\.literal\("yes"/);
assert.match(schema, /delivery_location/);
assert.match(schema, /destination_country/);
assert.match(schema, /website: z\.string\(\)\.max\(0/);
assert.match(route, /\.from\("contact_inquiries"\)\.insert/);
assert.match(route, /source_path: "\/business-supply"/);
assert.match(route, /inquiry_details: details/);
assert.match(route, /New \$\{siteConfig\.name\}.*enquiry from/);
assert.ok(route.indexOf(".insert({") < route.indexOf("sendEmail({"));
assert.match(admin, /detailLabels/);
assert.doesNotMatch(admin, /JSON\.stringify\(row\.inquiry_details/);
assert.match(redirect, /getActiveCampaignBySlug/);
assert.match(page, /Business & Export Supply \| Shields Farms/);
assert.match(form, /htmlFor=\{id\}/);
assert.match(form, /aria-describedby/);
assert.match(migration, /revoke all on public\.contact_inquiries from anon, authenticated/);
console.log("Business supply upgrade: 20 focused checks passed.");
