import assert from "node:assert/strict";
import test from "node:test";
import { candidateTavilyAssociation,buildCandidateTavilyQueries } from "../src/lib/sales-scout/research/tavily.ts";
import { contactsForCandidate,productionResearchCostCeiling,runSeedFirstProductionResearch } from "../src/lib/sales-scout/research/production.ts";
import type { ResearchCandidate,ResearchEvidence } from "../src/lib/sales-scout/research/types.ts";
import { evaluateTerritoryMatch,NIGERIAN_STATES_AND_FCT,normalizeNigerianState,salesScoutCampaignInputSchema,unsupportedStructuredCategories } from "../src/lib/sales-scout/territory.ts";

const observed="2026-08-02T10:00:00.000Z";
const evidence=(field:string,value:string,status:"verified"|"plausible"="verified"):ResearchEvidence=>({source:"geoapify_places",sourceUrl:"https://www.geoapify.com/place-details/?id=seed-1",observedAt:observed,field,value,confidence:status==="verified"?"high":"medium",verificationStatus:status});
function seed(city:string|null="Ikeja"):ResearchCandidate{return{sourceIdentities:{geoapify_places:"seed-1"},businessName:"Example Kitchen Limited",normalizedBusinessName:"example kitchen",requestedCategory:"Restaurant",requestedTerritory:{country:"Nigeria",state:"Lagos",city:"Ikeja",latitude:6.6018,longitude:3.3515,radiusKm:15},providerCategories:["catering.restaurant"],country:"Nigeria",state:"Lagos State",city,address:"12 Allen Avenue, Ikeja",latitude:6.6018,longitude:3.3515,website:null,phoneNumbers:["07032821293"],emailAddresses:[],whatsAppNumbers:[],instagram:[],facebook:[],tiktok:[],x:[],youtube:[],publicDescription:null,evidence:[evidence("businessName","Example Kitchen Limited"),evidence("requestedCategory","Restaurant"),evidence("country","Nigeria"),evidence("state","Lagos State"),...(city?[evidence("city",city)]:[]),evidence("phone","07032821293","plausible")],discoverySources:["geoapify_places"],researchIssues:[],firstObservedAt:observed,lastObservedAt:observed};}

test("all supported state aliases normalize and arbitrary campaign towns validate",()=>{assert.equal(NIGERIAN_STATES_AND_FCT.length,37);assert.equal(normalizeNigerianState("Lagos State"),"Lagos");assert.equal(normalizeNigerianState("FCT"),"Federal Capital Territory");assert.equal(normalizeNigerianState("Abuja Federal Capital Territory"),"Federal Capital Territory");const parsed=salesScoutCampaignInputSchema.parse({name:"Akure pilot",status:"draft",country:"Nigeria",state:"Ondo",city:"Iju",targetCategories:["Restaurant"],productScope:null,deliverySummary:null,dailyReviewTarget:10,latitude:null,longitude:null,radiusKm:15,resultLimit:5,maxEnrichmentCandidates:2});assert.equal(parsed.city,"Iju");assert.deepEqual(unsupportedStructuredCategories(["Restaurant","School"]),["School"]);});
test("territory radius evidence supports a missing provider city without fabricating it",()=>{const match=evaluateTerritoryMatch({providerCountry:"Nigeria",providerState:"Lagos State",providerCity:null,latitude:6.6018,longitude:3.3515,campaign:{state:"Lagos",city:"Ikeja",latitude:6.6018,longitude:3.3515,radiusKm:5}});assert.equal(match.matched,true);assert.equal(match.basis,"coordinates_within_campaign_radius");assert.equal(match.provider.city,null);assert.equal(match.distanceKm,0);});
test("candidate-specific Tavily association is deterministic and broad documents are rejected",()=>{const candidate=seed();assert.equal(buildCandidateTavilyQueries(candidate).length,2);assert.equal(candidateTavilyAssociation(candidate,{title:"Example Kitchen Limited contact",url:"https://examplekitchen.ng",content:"12 Allen Avenue Ikeja"}),true);assert.equal(candidateTavilyAssociation(candidate,{title:"Best restaurants in Lagos",url:"https://newspaper.example/best-restaurants",content:"A general city guide"}),false);});
test("Geoapify contact stays plausible while official-site evidence becomes verified",()=>{const candidate=seed();assert.equal(contactsForCandidate(candidate)[0]?.confidence,"plausible");const verified={...candidate,evidence:[...candidate.evidence,{...evidence("phone","07032821293"),source:"official_website" as const,sourceUrl:"https://examplekitchen.ng/contact"}]};assert.equal(contactsForCandidate(verified)[0]?.confidence,"verified");});
test("seed-first pipeline stages structured seeds after optional enrichment failure",async()=>{const result=await runSeedFirstProductionResearch({territory:{country:"Nigeria",state:"Lagos",city:"Ikeja",latitude:6.6018,longitude:3.3515,radiusKm:15},categories:["Restaurant"],resultLimit:5,maxEnrichmentCandidates:1,tavilyConfigured:true},{geoapify:async()=>({provider:"geoapify_places",candidates:[seed(null)],rawResultCount:1,estimatedCredits:1,resolvedTerritory:{latitude:6.6018,longitude:3.3515}}),tavily:async()=>{throw new Error("TAVILY_TIMEOUT");},website:async()=>[]});assert.equal(result.structuredSeedCount,1);assert.equal(result.candidates.length,1);assert.equal(result.candidates[0].candidate.city,null);assert.equal(result.candidates[0].manualReviewReady,true);assert.equal(result.candidates[0].outreachReady,false);assert.equal(result.candidates[0].highestContactConfidence,"plausible");assert.ok(result.warnings.includes("TAVILY_TIMEOUT"));});
test("production bounds cap enrichment and expose an offline cost ceiling",()=>{assert.deepEqual(productionResearchCostCeiling({categories:2,coordinatesConfigured:false,resultLimit:5,maxEnrichmentCandidates:6}),{maximumGeoapifyCalls:3,maximumTavilySearches:12,maximumOfficialWebsites:6,maximumOfficialWebsitePages:30,maximumStagedCandidates:10});assert.rejects(()=>runSeedFirstProductionResearch({territory:{country:"Nigeria",state:"Lagos",city:"Ikeja"},categories:["Restaurant"],resultLimit:101,maxEnrichmentCandidates:6,tavilyConfigured:false}));});
