"use server";
import {z} from "zod";
import {revalidatePath} from "next/cache";
import {requireAdmin} from "@/src/lib/admin-auth";
import {createAdminSupabaseClient} from "@/src/lib/supabase/admin";
const text=(max=500)=>z.string().trim().min(1).max(max);
const optional=(max=1000)=>z.string().trim().max(max).transform((v)=>v||null);
export async function createCampaignSpendAction(formData:FormData){await requireAdmin();const value=z.object({campaign_id:z.string().uuid(),amount:z.coerce.number().nonnegative(),currency:z.string().regex(/^[A-Z]{3}$/),spend_date:z.string().date(),spend_type:z.enum(["paid_social","printed_flyers","design","creator_influencer","photography_video","delivery_subsidy","other"]),note:optional()}).parse(Object.fromEntries(formData));await createAdminSupabaseClient().from("marketing_campaign_spend").insert(value);revalidatePath("/admin/marketing/campaigns")}
export async function createProspectAction(formData:FormData){await requireAdmin();const value=z.object({business_name:text(200),business_category:optional(120),stage:z.enum(["identified","contacted","responded","requirements_received","proposal_sent","negotiating","trial_order","recurring_customer","won","lost"]),requirements:optional(2000),estimated_value:z.coerce.number().nonnegative(),expected_frequency:optional(120),source:optional(120),assigned_follow_up_at:optional(80),notes:optional(3000)}).parse(Object.fromEntries(formData));await createAdminSupabaseClient().from("marketing_prospects").insert({...value,assigned_follow_up_at:value.assigned_follow_up_at||null});revalidatePath("/admin/marketing/prospects");revalidatePath("/admin/marketing/overview")}
export async function createSocialActivityAction(formData:FormData){await requireAdmin();const value=z.object({platform:text(80),content_type:text(120),publication_url:optional(500),scheduled_at:optional(80),status:z.enum(["planned","scheduled","published","cancelled"]),notes:optional(2000)}).parse(Object.fromEntries(formData));await createAdminSupabaseClient().from("marketing_social_activities").insert(value);revalidatePath("/admin/marketing/social");revalidatePath("/admin/marketing/overview")}
export async function createAffiliateConversionAction(formData:FormData){await requireAdmin();const value=z.object({partner_id:z.string().uuid(),offer_id:z.string().uuid().or(z.literal("")).transform((v)=>v||null),external_transaction_reference:text(200),conversion_date:z.string().date(),commission_amount:z.coerce.number().nonnegative(),currency:z.string().regex(/^[A-Z]{3}$/),status:z.enum(["pending","approved","paid","rejected","reversed"]),note:optional(1000)}).parse(Object.fromEntries(formData));await createAdminSupabaseClient().from("affiliate_conversions").insert(value);revalidatePath("/admin/marketing/content-performance")}
