import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminHeader } from "@/src/components/admin";
import { AdminSubnav } from "@/src/components/content-admin/admin-subnav";
import { CrudManager } from "@/src/components/content-admin/crud-manager";
import { contentPublicConfig } from "@/src/config/site";
import { loadAdminEntity, loadAdminOptions } from "@/src/lib/content-admin";

export const dynamic = "force-dynamic";

export default async function OffersPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  if (!contentPublicConfig.affiliateEnabled) notFound();
  const filters = await searchParams;
  const [data, options] = await Promise.all([loadAdminEntity("offers", filters), loadAdminOptions()]);
  const partners = [{ value: "", label: "Choose partner" }, ...options.partners.map((partner) => ({ value: String(partner.id), label: String(partner.name) }))];
  const basis = [{value:"editorial_research",label:"Editorial research"},{value:"merchant_information",label:"Merchant information"},{value:"personally_tested",label:"Personally tested"}];
  return <div><AdminHeader title="Affiliate Offers" body="Manage merchant-supplied affiliate links and editorial recommendation metadata." /><AdminSubnav type="affiliate" />{options.partners.length === 0 ? <div className="mb-6 rounded-lg bg-amber-50 p-4 text-sm font-bold text-amber-900">Create an affiliate partner before adding an offer. <Link className="underline" href="/admin/affiliate/partners">Go to partners</Link></div> : null}<CrudManager entity="offers" title="Offers" createLabel="Create Offer" records={data.records} filters={filters} count={data.count} page={data.page} pageSize={data.pageSize} totalPages={data.totalPages} searchPlaceholder="Search offers" emptyTitle="No offers yet" emptyBody={options.partners.length === 0 ? "Create an affiliate partner before adding an offer." : "Create offers after adding affiliate partners."} loadError={data.error} createDisabledReason={options.partners.length === 0 ? "Create an affiliate partner before adding an offer." : undefined} fields={[{name:"partner_id",label:"Partner *",type:"select",required:true,options:partners},{name:"title",label:"Title *",required:true},{name:"slug",label:"Slug *",required:true},{name:"destination_url",label:"Destination affiliate URL *",type:"url",required:true,help:"Only HTTP/HTTPS URLs are accepted."},{name:"short_description",label:"Short description *",type:"textarea",required:true},{name:"image_url",label:"Image URL",type:"url"},{name:"image_alt",label:"Image alt text"},{name:"button_label",label:"Button label"},{name:"display_price",label:"Optional display price"},{name:"currency",label:"Currency"},{name:"price_last_checked_at",label:"Price last checked",type:"date"},{name:"available_regions",label:"Available regions",help:"Comma-separated."},{name:"recommendation_basis",label:"Recommendation basis *",type:"select",required:true,options:basis,help:"Personally tested only when genuinely used/tested. Editorial research for documented comparison. Merchant information when relying on merchant/manufacturer info."},{name:"is_featured",label:"Featured",type:"checkbox"},{name:"internal_commission_note",label:"Internal commission note",type:"textarea",help:"Admin-only. Never public."},{name:"is_active",label:"Active",type:"checkbox"}]} columns={[{key:"title",label:"Offer"},{key:"partner_name",label:"Partner"},{key:"recommendation_basis",label:"Basis"},{key:"click_count",label:"Clicks",format:"number"},{key:"post_count",label:"Posts",format:"number"},{key:"is_active",label:"Status",format:"status"}]} /></div>;
}
