import Link from "next/link";
import { notFound } from "next/navigation";
import { CaptureCandidateForm,DismissCandidateForm,CandidateContactActions } from "@/src/components/sales-scout/discovery-candidate-actions";
import { requireAdmin } from "@/src/lib/admin-auth";
import { isSalesScoutDiscoveryEnabled,isSalesScoutEnabled } from "@/src/lib/sales-scout/access";
import { getSalesScoutDiscoveryCandidate,previewStagedSalesScoutCandidate } from "@/src/lib/sales-scout/discovery/server";

export const dynamic="force-dynamic";
export default async function Page({params}:{params:Promise<{candidateId:string}>}){await requireAdmin();if(!isSalesScoutEnabled()||!isSalesScoutDiscoveryEnabled())notFound();const{candidateId}=await params;const detail=await getSalesScoutDiscoveryCandidate(candidateId);const candidate=detail.candidate;let preview:Awaited<ReturnType<typeof previewStagedSalesScoutCandidate>>|null=null;if(detail.readiness.candidate){try{preview=await previewStagedSalesScoutCandidate(candidateId);}catch{preview=null;}}const final=["captured","dismissed"].includes(candidate.status);const territory=candidate.territory_match_evidence;return <main className="space-y-5 p-6"><Link href={`/admin/marketing/sales-scout/discover?campaignId=${candidate.scout_campaign_id}`} className="font-bold text-green-800">Back to discovery</Link><section className="rounded-xl border bg-white p-5"><h1 className="text-3xl font-bold">{candidate.business_name}</h1><p>{candidate.mapped_campaign_category??candidate.provider_category} · Geoapify identity {candidate.geoapify_place_id}</p>{candidate.provider_source_url?<a href={candidate.provider_source_url} target="_blank" rel="noreferrer" className="text-green-800 underline">Open provider evidence</a>:null}<p className="mt-3">{candidate.publicDescription??"No public description."}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="font-bold">Provider geography</dt><dd>{[candidate.city,candidate.state,candidate.country_code].filter(Boolean).join(", ")||"Provider city unavailable"}</dd></div><div><dt className="font-bold">Campaign territory</dt><dd>{String((territory.campaign as Record<string,unknown>|undefined)?.city??"")}, {String((territory.campaign as Record<string,unknown>|undefined)?.state??"")}</dd></div><div><dt className="font-bold">Territory match</dt><dd>{territory.matched?`Verified: ${String(territory.basis).replaceAll("_"," ")}`:"Not verified"}{candidate.distance_km!=null?` · ${candidate.distance_km} km`:""}</dd></div><div><dt className="font-bold">Address</dt><dd>{candidate.full_address??"Unavailable"}</dd></div><div><dt className="font-bold">Coordinates</dt><dd>{candidate.latitude!=null?`${candidate.latitude}, ${candidate.longitude}`:"Unavailable"}</dd></div><div><dt className="font-bold">Research status</dt><dd>{candidate.enrichment_status}</dd></div></dl></section>
<section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Public contacts</h2><p className="text-sm">Manual review ready: {candidate.manual_review_ready?"yes":"no"} · Outreach ready with verified route: {candidate.outreach_ready?"yes":"no"}</p><div className="mt-3 grid gap-3">{candidate.contact_evidence.map(contact=><article key={`${contact.route}:${contact.normalizedIdentity}`} className="rounded border p-3"><div className="flex flex-wrap justify-between gap-2"><b>{contact.route}: {contact.displayValue}</b><span className={contact.confidence==="verified"?"text-green-800":"text-amber-800"}>{contact.confidence}</span></div><p className="text-xs">Source: {contact.sourceType} · observed {new Date(contact.observedAt).toLocaleString("en-NG")}</p><a href={contact.sourceUrl} target="_blank" rel="noreferrer" className="text-sm text-green-800 underline">Open contact evidence</a><CandidateContactActions contact={contact}/></article>)}{candidate.contact_evidence.length===0?<p>Needs research: no normalized public contact is available.</p>:null}</div></section>
<section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Research and matching</h2><p>Status: {candidate.status}</p><p>Exact CRM prospect: {detail.exactProspect?.businessName??"None"}</p><p>Captured CRM prospect: {detail.capturedProspect?<Link className="text-green-800 underline" href={`/admin/marketing/sales-scout/${detail.capturedProspect.id}`}>{detail.capturedProspect.businessName}</Link>:"None"}</p>{detail.readiness.blockers.map(blocker=><p key={blocker} className="text-amber-800">{blocker}</p>)}{candidate.research_issues.map(issue=><p key={issue}>{issue}</p>)}</section>
<section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Discovery history</h2>{detail.history.map(item=><p key={item.discovery_run_id}>{new Date(item.created_at).toLocaleString("en-NG")} · exact {String(item.is_exact_duplicate)} · warnings {item.soft_match_warning_count}</p>)}</section>
{!final&&preview?<section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Capture or attach</h2><p>Plausible contacts remain labelled and require owner review; capture does not verify them.</p>{preview.allowedResolutionChoices.map(choice=><CaptureCandidateForm key={JSON.stringify(choice)} candidateId={candidateId} choice={choice}/>)}</section>:null}{!final?<DismissCandidateForm candidateId={candidateId}/>:null}{candidate.status==="dismissed"?<p>Dismissed: {candidate.dismissal_reason}</p>:null}</main>;}