"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { saveCampaignAction } from "@/app/admin/(protected)/marketing/sales-scout/actions";
import { NIGERIAN_STATES_AND_FCT, STRUCTURED_GEOAPIFY_CATEGORIES } from "@/src/lib/sales-scout/territory";
import { RESEARCH_CATEGORIES } from "@/src/lib/sales-scout/research/types";
import type { SalesScoutCampaignDto } from "@/src/lib/sales-scout/server";

const input="mt-1 h-11 w-full rounded-lg border px-3";
export function SalesScoutCampaignForm({campaign}:{campaign?:SalesScoutCampaignDto}){
  const router=useRouter();const[pending,start]=useTransition();const[message,setMessage]=useState("");
  const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const payload={campaignId:campaign?.campaignId,name:form.get("name"),status:form.get("status"),country:"Nigeria",state:form.get("state"),city:form.get("city"),targetCategories:form.getAll("targetCategories"),productScope:form.get("productScope"),deliverySummary:form.get("deliverySummary"),dailyReviewTarget:form.get("dailyReviewTarget"),latitude:String(form.get("latitude")||"")?Number(form.get("latitude")):null,longitude:String(form.get("longitude")||"")?Number(form.get("longitude")):null,radiusKm:form.get("radiusKm"),resultLimit:form.get("resultLimit"),maxEnrichmentCandidates:form.get("maxEnrichmentCandidates")};start(async()=>{const data=new FormData();data.set("payload",JSON.stringify(payload));const result=await saveCampaignAction(data);setMessage(result.message);if(result.ok)router.refresh();});};
  return <form onSubmit={submit} className="grid gap-4 rounded-xl border bg-white p-5">
    <div className="grid gap-3 md:grid-cols-3"><label className="font-bold md:col-span-2">Campaign name<input name="name" required maxLength={120} defaultValue={campaign?.name??""} className={input}/></label><label className="font-bold">Status<select name="status" defaultValue={campaign?.status??"draft"} className={input}>{["draft","active","paused","completed"].map(x=><option key={x}>{x}</option>)}</select></label></div>
    <div className="grid gap-3 md:grid-cols-3"><label className="font-bold">Country<input readOnly value="Nigeria" className={input}/></label><label className="font-bold">State / FCT<select name="state" required defaultValue={campaign?.state??"Lagos"} className={input}>{NIGERIAN_STATES_AND_FCT.map(state=><option key={state}>{state}</option>)}</select></label><label className="font-bold">City or town<input name="city" required maxLength={120} defaultValue={campaign?.city??""} className={input}/></label></div>
    <fieldset><legend className="font-bold">Target categories</legend><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{RESEARCH_CATEGORIES.map(category=>{const supported=(STRUCTURED_GEOAPIFY_CATEGORIES as readonly string[]).includes(category);return <label key={category} className="rounded border p-2"><input type="checkbox" name="targetCategories" value={category} defaultChecked={campaign?.targetCategories.includes(category)??false} className="mr-2"/>{category}<span className={`ml-2 text-xs ${supported?"text-green-700":"text-amber-700"}`}>{supported?"structured":"connector pending"}</span></label>;})}</div><p className="mt-2 text-sm text-amber-800">Connector-pending categories can be saved, but discovery will not substitute broad web searches.</p></fieldset>
    <label className="font-bold">Product scope<textarea name="productScope" maxLength={1000} defaultValue={campaign?.productScope??""} className="mt-1 min-h-20 w-full rounded-lg border p-3"/></label><label className="font-bold">Delivery summary<textarea name="deliverySummary" maxLength={1000} defaultValue={campaign?.deliverySummary??""} className="mt-1 min-h-20 w-full rounded-lg border p-3"/></label>
    <div className="grid gap-3 sm:grid-cols-3"><label className="font-bold">Daily review target<input name="dailyReviewTarget" type="number" min="1" max="500" required defaultValue={campaign?.dailyReviewTarget??20} className={input}/></label><label className="font-bold">Radius (km)<input name="radiusKm" type="number" min="1" max="50" required defaultValue={campaign?.discoveryRadiusKm??20} className={input}/></label><label className="font-bold">Results/category<input name="resultLimit" type="number" min="1" max="100" required defaultValue={campaign?.discoveryDefaultLimit??20} className={input}/></label></div>
    <div className="grid gap-3 sm:grid-cols-3"><label className="font-bold">Enrichment cap<input name="maxEnrichmentCandidates" type="number" min="1" max="20" required defaultValue={campaign?.maxEnrichmentCandidates??6} className={input}/></label><label className="font-bold">Latitude (optional)<input name="latitude" type="number" step="any" min="-90" max="90" defaultValue={campaign?.discoveryLatitude??""} className={input}/></label><label className="font-bold">Longitude (optional)<input name="longitude" type="number" step="any" min="-180" max="180" defaultValue={campaign?.discoveryLongitude??""} className={input}/></label></div>
    <p className="text-sm text-stone-600">Coordinates are optional; Geoapify may resolve the city and state on the first run. Saving never starts discovery.</p><button disabled={pending} className="h-11 rounded-full bg-green-800 font-bold text-white disabled:opacity-50">{pending?"Saving...":"Save campaign"}</button>{message?<p role="status" className="font-bold">{message}</p>:null}
  </form>;
}
