"use client";

import { useMemo,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { approveOutreachAction,markOutreachSentAction,recordOutreachOutcomeAction,saveOutreachDraftAction } from "@/app/admin/(protected)/marketing/sales-scout/actions";
import { buildManualHandoff,generateDeterministicOutreachDraft,nextOutreachSequence,recommendOutreachChannels } from "@/src/lib/sales-scout/outreach";

type Channel={id:string;platform:string;handle_or_value:string;profile_url:string|null;is_active:boolean};
type Outreach={id:string;channel_id:string;sequence_number:number;status:string;draft_text:string|null;approved_text:string|null;sent_text:string|null;sent_at:string|null;due_at:string|null;reply_summary:string|null};
export function OutreachControls({prospect,campaign,channels,outreaches}:{prospect:Record<string,unknown>;campaign:{productScope:string|null;deliverySummary:string|null};channels:Channel[];outreaches:Outreach[]}){
  const router=useRouter();const[pending,start]=useTransition();const[message,setMessage]=useState("");const recommended=useMemo(()=>recommendOutreachChannels(channels.map(c=>({id:c.id,platform:c.platform,handleOrValue:c.handle_or_value,profileUrl:c.profile_url,active:c.is_active}))),[channels]);const[channelId,setChannelId]=useState(recommended[0]?.id??"");const sequence=nextOutreachSequence(outreaches);const generated=sequence?generateDeterministicOutreachDraft({sequenceNumber:sequence,businessName:String(prospect.business_name),businessCategory:String(prospect.business_category??"business"),city:String(prospect.city??""),state:prospect.state?String(prospect.state):null,productScope:campaign.productScope,deliverySummary:campaign.deliverySummary}):"";const[draft,setDraft]=useState(generated);const run=(operation:()=>Promise<{ok:boolean;message:string}>)=>start(async()=>{const result=await operation();setMessage(result.message);if(result.ok)router.refresh();});const selected=recommended.find(c=>c.id===channelId);const approved=outreaches.find(o=>o.status==="approved");const approvedChannel=approved?recommended.find(channel=>channel.id===approved.channel_id):undefined;const handoff=approved&&approvedChannel?buildManualHandoff({platform:approvedChannel.platform,value:approvedChannel.handleOrValue,profileUrl:approvedChannel.profileUrl,message:approved.approved_text??""}):null;
  if(prospect.do_not_contact_at)return <section className="rounded-xl bg-red-100 p-5"><h2 className="text-xl font-bold">Outreach blocked</h2><p>Do-not-contact suppression cannot be bypassed or removed here.</p></section>;
  return <section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Human-controlled outreach</h2><p>No message is sent automatically. Opening a handoff does not mark anything sent.</p><label className="block font-bold">Channel<select value={channelId} onChange={e=>setChannelId(e.target.value)} className="mt-1 h-11 w-full rounded border px-3">{recommended.map(c=><option key={c.id} value={c.id}>{c.platform}: {c.handleOrValue}</option>)}</select></label>
    {sequence&&selected?<><p className="font-bold">Draft {sequence} of 3</p><textarea value={draft} onChange={e=>setDraft(e.target.value)} maxLength={4000} className="min-h-40 w-full rounded border p-3"/><div className="flex flex-wrap gap-2"><button disabled={pending} onClick={()=>run(async()=>{const form=new FormData();form.set("prospectId",String(prospect.id));form.set("channelId",selected.id);form.set("sequenceNumber",String(sequence));form.set("draftText",draft);return saveOutreachDraftAction(form);})} className="rounded-full border px-4 py-2 font-bold">Save editable draft</button>{outreaches.find(o=>o.sequence_number===sequence&&o.status==="draft")?<button disabled={pending} onClick={()=>{const item=outreaches.find(o=>o.sequence_number===sequence&&o.status==="draft")!;run(async()=>{const form=new FormData();form.set("outreachId",item.id);form.set("approvedText",draft);return approveOutreachAction(form);});}} className="rounded-full bg-green-800 px-4 py-2 font-bold text-white">Approve draft</button>:null}</div></>:<p>Maximum of three outreach attempts reached.</p>}
    {approved?<div className="rounded border border-amber-300 bg-amber-50 p-4"><h3 className="font-bold">Approved manual handoff</h3>{handoff?<a href={handoff} target={handoff.startsWith("http")?"_blank":undefined} rel="noreferrer" className="mt-2 inline-block rounded-full bg-green-800 px-4 py-2 font-bold text-white">Open {approvedChannel?.platform} handoff</a>:<p>Select the approved outreach channel to open a handoff.</p>}<p className="mt-2 text-sm">Copy the approved text for social profiles or a phone call. You must press Send or place the call yourself.</p><label className="mt-3 block font-bold">Sender account label<input id="senderLabel" className="mt-1 h-11 w-full rounded border px-3" placeholder="e.g. Shields Farms WhatsApp"/></label><label className="mt-2 flex gap-2"><input id="sentConfirmed" type="checkbox"/>I confirm I manually sent this exact message.</label><button disabled={pending} onClick={()=>{const label=(document.getElementById("senderLabel") as HTMLInputElement).value;const confirmed=(document.getElementById("sentConfirmed") as HTMLInputElement).checked;run(async()=>{const form=new FormData();form.set("outreachId",approved.id);form.set("sentText",approved.approved_text??"");form.set("senderAccountLabel",label);form.set("confirmed",confirmed?"yes":"no");return markOutreachSentAction(form);});}} className="mt-2 rounded-full border border-green-800 px-4 py-2 font-bold">Mark sent after manual send</button></div>:null}
    {outreaches.filter(o=>["sent","no_response"].includes(o.status)).map(item=><form key={item.id} action={form=>run(()=>recordOutreachOutcomeAction(form))} className="grid gap-2 rounded border p-4"><input type="hidden" name="outreachId" value={item.id}/><b>Record outcome for outreach {item.sequence_number}</b><select name="outcome" className="h-11 rounded border px-3">{["interested","warm","neutral","not_interested","opt_out","irrelevant","wants_pricing","wants_product_list","wants_call","referred","no_response","cancelled"].map(x=><option key={x}>{x}</option>)}</select><textarea name="summary" required maxLength={2000} placeholder="Reply or outcome summary" className="min-h-20 rounded border p-3"/><input name="commercialSignal" maxLength={500} placeholder="Next recommended action or commercial signal" className="h-11 rounded border px-3"/><button disabled={pending} className="rounded-full border px-4 py-2 font-bold">Record outcome</button></form>)}
    {message?<p role="status" className="font-bold">{message}</p>:null}
  </section>;
}
