import { notFound } from "next/navigation";
import { AdminHeader, StatCard } from "@/src/components/admin";
import { AdminSubnav } from "@/src/components/content-admin/admin-subnav";
import { contentPublicConfig } from "@/src/config/site";
import { loadCommerceReport } from "@/src/lib/content-admin";

export const dynamic = "force-dynamic";

export default async function ContentCommercePage() {
  if (!contentPublicConfig.hubEnabled) notFound();
  const report = await loadCommerceReport();
  return <div><AdminHeader title="Content Commerce" body="Content-assisted attribution reporting. This is attribution, not direct causation." /><AdminSubnav /><div className="grid gap-4 md:grid-cols-4"><StatCard label="Product clicks" value={String(report.productClicks)} note="Consent-permitted content product clicks." /><StatCard label="Content-assisted orders" value={String(report.contentAssistedOrders)} note="Orders with content attribution." /><StatCard label="Paid orders" value={String(report.contentAssistedPaidOrders)} note="Paid content-assisted orders." /><StatCard label="Paid revenue" value={report.contentAssistedPaidRevenue} note="Paid content-assisted revenue." /></div><div className="mt-6 grid gap-6 lg:grid-cols-2">{report.productClicks === 0 && report.contentAssistedOrders === 0 && report.relationships.length === 0 ? <section className="rounded-lg bg-white p-5 text-sm text-stone-600 shadow-sm lg:col-span-2">No content-assisted activity has been recorded yet.</section> : null}<Panel title="Top posts by product clicks" rows={report.topPosts} /><Panel title="Top products clicked from content" rows={report.topProducts} /></div><section className="mt-6 rounded-lg bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-green-950">Recent content-assisted orders</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="text-left text-stone-500"><th className="py-2">Reference</th><th>Payment</th><th>Total</th><th>Date</th></tr></thead><tbody>{(report.recentOrders as Array<Record<string, unknown>>).map((order)=><tr key={String(order.id)} className="border-t border-stone-100"><td className="py-3 font-bold text-green-950">{String(order.order_reference)}</td><td>{String(order.payment_status)}</td><td>{String(order.total_amount)}</td><td>{new Date(String(order.created_at)).toLocaleDateString("en-NG")}</td></tr>)}</tbody></table></div></section><section className="mt-6 rounded-lg bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-green-950">Post/product relationships</h2><p className="mt-2 text-sm text-stone-600">Products attached in the article editor power live product blocks and attribution links.</p><div className="mt-4 grid gap-2">{(report.relationships as Array<Record<string, unknown>>).map((row, index)=><div key={index} className="rounded-lg border border-stone-100 p-3 text-sm"><strong>{relation(row.content_posts,"title")}</strong>{" -> "}{relation(row.products,"name")}</div>)}</div></section></div>;
}
function Panel({ title, rows }: { title:string; rows:Array<{label:string;count:number}> }) { return <section className="rounded-lg bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-green-950">{title}</h2><div className="mt-4 grid gap-2">{rows.length ? rows.map((row)=><div key={row.label} className="flex justify-between rounded-lg bg-green-50 p-3 text-sm"><span>{row.label}</span><strong>{row.count}</strong></div>) : <p className="text-sm text-stone-600">No activity yet.</p>}</div></section>; }
function relation(value: unknown, key: string) { const row = Array.isArray(value) ? value[0] as Record<string,unknown>|undefined : value as Record<string,unknown>|undefined; return String(row?.[key] ?? "-"); }
