import {AdminHeader} from "@/src/components/admin";
import {MarketingNav} from "@/src/components/marketing-command-ui";
import {requireAdmin} from "@/src/lib/admin-auth";
import {createAdminSupabaseClient} from "@/src/lib/supabase/admin";
import {ga4Configuration,getGa4Summary} from "@/src/lib/ga4-data";
import {googleIntegration} from "@/src/lib/analytics";
export const dynamic="force-dynamic";
const zero="00000000-0000-0000-0000-000000000000";
export default async function Page(){
  await requireAdmin();const db=createAdminSupabaseClient();
  const[campaigns,clicks,orders,offers,ga,prospects,activities,stageRpc,activityRpc]=await Promise.all([
    db.from("marketing_campaigns").select("id,slug,target_path"),db.from("marketing_campaign_clicks").select("id,campaign_id").limit(1),db.from("orders").select("id,order_reference,payment_status,first_touch_attribution,last_touch_attribution").eq("payment_status","paid").limit(2000),db.from("affiliate_offers").select("id,is_active").limit(1000),getGa4Summary(),
    db.from("marketing_prospects").select("id,stage,updated_at").order("updated_at",{ascending:false}).limit(1),
    db.from("marketing_prospect_activities").select("id,prospect_id,activity_type,stage_from,stage_to,summary,occurred_at,next_follow_up_at,created_by,created_at").order("occurred_at",{ascending:false}).limit(1),
    db.rpc("change_marketing_prospect_stage",{p_prospect_id:zero,p_stage:"identified",p_summary:null,p_created_by:zero}),
    db.rpc("record_marketing_prospect_activity",{p_prospect_id:zero,p_activity_type:"note",p_summary:"Schema validation only",p_occurred_at:null,p_next_follow_up_at:null,p_created_by:zero})
  ]);
  const paid=orders.data??[];const rpcVisible=(error:{code?:string}|null)=>!error||error.code==="P0002";
  const checks:Array<[string,unknown]>=[["Campaign schema readable",!campaigns.error],["Campaign redirect clicks observed",(clicks.data?.length??0)>0],["Campaign UTM IDs available",(campaigns.data??[]).every((x)=>Boolean(x.slug))],["First-touch attribution observed",paid.some((x)=>x.first_touch_attribution)],["Last-touch attribution observed",paid.some((x)=>x.last_touch_attribution)],["Paid-order attribution query functional",!orders.error],["GA measurement ID valid",googleIntegration().valid],["GA Data API",ga4Configuration().configured?"Configured":"Intentionally absent"],["Recent page views via API",ga.available?Number(ga.metrics.screenPageViews||0)>0:"Unavailable"],["Invalid campaign target paths",(campaigns.data??[]).filter((x)=>!x.target_path?.startsWith("/")||x.target_path.startsWith("//")).length===0],["Orders without attribution",paid.filter((x)=>!x.first_touch_attribution&&!x.last_touch_attribution).length],["Unavailable affiliate offers",(offers.data??[]).filter((x)=>!x.is_active).length]];
  const workflow:Array<[string,unknown]>=[["marketing_prospects accessible",!prospects.error],["marketing_prospect_activities accessible",!activities.error],["Required activity columns visible",!activities.error],["Stage constraints reconciled","Verify with database/verify-marketing-prospect-workflow.sql"],["Activity-type constraint reconciled","Verify with database/verify-marketing-prospect-workflow.sql"],["Stage-change RPC available",rpcVisible(stageRpc.error)],["Activity RPC available",rpcVisible(activityRpc.error)],["Service-role RPC execution configured",rpcVisible(stageRpc.error)&&rpcVisible(activityRpc.error)],["PostgREST schema visible",!activities.error&&rpcVisible(stageRpc.error)],["Latest successful stage change",activities.data?.find((x)=>["stage_change","won","lost"].includes(x.activity_type))?.occurred_at??"None recorded"],["Latest successful activity",activities.data?.[0]?.occurred_at??"None recorded"]];
  const rows=(items:Array<[string,unknown]>)=><div className="rounded-xl border bg-white">{items.map(([label,value])=><div key={label} className="flex items-center justify-between gap-4 border-b p-4"><strong>{label}</strong><span>{typeof value==="boolean"?(value?"Ready":"Attention"):String(value)}</span></div>)}</div>;
  return <><AdminHeader title="Marketing data quality" body="Safe production checks. Revenue remains sourced from paid Supabase orders, never GA."/><MarketingNav/>{rows(checks)}<section className="mt-6"><h2 className="mb-3 text-xl font-bold text-green-950">Prospect workflow</h2>{rows(workflow)}<p className="mt-3 text-sm text-stone-600">The RPC availability probes use a nonexistent UUID and cannot change a prospect, create an activity, order, or revenue.</p></section><section className="mt-6 rounded-xl border bg-white p-5"><h2 className="font-bold">Non-revenue production test</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm"><li>Open a campaign /go/slug URL in a private browser.</li><li>Confirm redirect target and utm_id equal the campaign slug.</li><li>Confirm one redirect click appears here.</li><li>Use the read-only prospect workflow verifier; do not create or mark an order paid.</li><li>Use GA DebugView for safe test events only.</li></ol></section></>;
}
